config/routes.rb
Rails.application.routes.draw do
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  # get 'user/new' => "users#new"
  # post 'user/create' => "users#create"

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 250 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

    # 渡された文字列のハッシュ値を返す
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      reset_session
      log_in user
      redirect_to current_user
    else
      flash.now[:danger] = 'メールアドレスかパスワードが間違っています。'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            reset_session
            log_in @user
            flash[:notice] = "新規登録が完了しました。"
            redirect_to users_path
        else
            render 'new', status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "更新に成功しました。"
            redirect_to user_path(@user)
        else
            render 'edit', status: :unprocessable_entity
        end
    end

    def destroy
        User.find(params[:id]).destroy
        flash[:notice] = "削除しました。"
        redirect_to users_path, status: :see_other
    end

    private

        def user_params
        params.require(:user).permit(:name, :email, :password,
                                    :password_confirmation)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # ページごとの完全なタイトルを返す
    def full_title(page_title = '')
        base_title = "Skill Market"
        if page_title.empty?
        base_title
        else
        "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # 渡されたユーザーでログインする
    def log_in(user)
        session[:user_id] = user.id
    end

    # 現在ログイン中のユーザーを返す（いる場合）
    def current_user
        if session[:user_id]
            @current_user ||= User.find_by(id: session[:user_id])
        end
    end

    # ログインしているかの確認をする
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header>
    <div class="container">
        <div class="header-title">
            <%= link_to("Skill Market", users_path)%>
        </div>

        <div class="header-nav">
            <nav>
            <% if logged_in? %>
                <li><%= link_to(current_user.name, current_user)%></li>
                <li><%= link_to("ログアウト", logout_path)%></li>
            <% else %>
                <li><%= link_to("ログイン", login_path)%></li>
                <li><%= link_to("サインアップ", new_user_path)%></li>
            <% end %>
            </nav>
        </div>
    </div>
</header>

app/views/users/edit.html.erb
<% provide(:title, 'Edit user') %>
<div class="container">
    <div class="text-center">
        <h1>編集画面</h1>
    </div>

    <div class="form-width">
        <%= form_with(model: @user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name, "名前" %><br>
            <%= f.text_field :name, class: 'form-control' %><br><br>

            <%= f.label :email, "メールアドレス" %><br>
            <%= f.email_field :email, class: 'form-control' %><br><br>

            <%= f.label :password, "パスワード" %><br>
            <%= f.password_field :password, class: 'form-control' %><br><br>

            <%= f.label :password_confirmation, "パスワード（確認用）" %><br>
            <%= f.password_field :password_confirmation, class: 'form-control' %><br><br>

            <%= f.submit "更新", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<h1>Hello,World!!</h1>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container">
    <div class="text-center">
        <h1>Sign up</h1>
    </div>

    <div class="form-width">
        <%= form_with(model: @user) do |f| %>
            <%= render 'shared/error_messages' %>

            <%= f.label :name, "名前" %><br>
            <%= f.text_field :name, class: 'form-control' %><br><br>

            <%= f.label :email, "メールアドレス" %><br>
            <%= f.email_field :email, class: 'form-control' %><br><br>

            <%= f.label :password, "パスワード" %><br>
            <%= f.password_field :password, class: 'form-control' %><br><br>

            <%= f.label :password_confirmation, "パスワード（確認用）" %><br>
            <%= f.password_field :password_confirmation, class: 'form-control' %><br><br>

            <%= f.submit "決定", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, 'Show user') %>
<div class="container">
    <p>名前:<%= @user.name%></p>
    <p>メアド:<%= @user.email%></p>

    <%= link_to "編集",edit_user_path(@user) %>
    <%= link_to "削除",user_path(@user), data: { turbo_method: :delete }%>
</div>